@startuml
'https://plantuml.com/class-diagram

class  AdministrationProcessDto {

- String snsUserNumber;
- String age;
- Vaccine vaccine;
- Schedule schedule;
+ public AdministrationProcessDto(String snsUserNumber, String age, Vaccine vaccine, Schedule schedule) {
+ public String getSnsUserNumber()
+ public String getAge()
+
}
@enduml