@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as administrator

participant ":RegisterVaccinationCenterUI" as ui
participant ":RegisterVaccinationCenterController" as controller

participant "VaccinationCenterStore" as store
participant ":Company" as company
participant "HealthCareCentre" as health

activate administrator

administrator -> ui : requests to register a new vaccination center
activate ui

ui --> administrator : shows types of vaccination centers(mass vaccination center/healthcarecenter) and asks to select one
deactivate ui
administrator -> ui : selects a healthcare centre
activate ui
ui -> administrator : requests data(pandemic to respond to,name,address,phone number,e-mail address,fax number,website address,opening/closing hours,slot duration and the maximum number of vaccines that can be given per slot)
deactivate ui
administrator -> ui : inputs the data
activate ui
ui --> controller : createHealthCareCenter(String pandemic,String name,String address,int phonenumber,int faxnumber,string website address,string openinghours,string closinghours,int slotduration,int maxvaccines)
deactivate ui
controller --> company : VaccinationCenterStore=getVaccinationCenterStore()
controller -> store : VaccinationCentre=registerVaccinationCenter(data)
deactivate controller
store --> health : create(data)
deactivate store
health --> health: validateinformation()
deactivate health
store-->store:validateVaccinationCentre(Vaccinationcentre)
deactivate store
ui --> administrator : shows the data and asks for confirmation
deactivate ui
administrator --> ui : confirms/deny the information
deactivate administrator
ui --> administrator : informs success/failure message
@enduml