package app.domain.utils;



import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Class to save the passwords generated by the system
 * @author Diogo Teixeira<1200904@isep.ipp.pt>
 */
public class PasswordSaver {

    /**
     * Method to save to a file the passwords
     * @param email log in e-mail
     * @param password log in password
     */
    public static void saveSnsUserPassword(String email, String password) throws IOException {

        String path = "out/SnsUsersPassword.txt";
        File passwords = new File(path);
        BufferedWriter out;

        if(passwords.exists()){
            FileWriter fstream = new FileWriter(path, true); //true tells to append data.
            out = new BufferedWriter(fstream);
            out.write("\nE-mail:" + email + "\nPassword:" + password);
            out.close();
        }else{

            FileWriter fileWriter = new FileWriter(path);
            fileWriter.write("SnsUsers Passwords:\n\nE-mail:" + email + "\nPassword:" + password);
            fileWriter.close();

        }

    }

    /**
     * Method to save to a file the passwords
     * @param email log in e-mail
     * @param password log in password
     */
    public static void saveEmployeesPassword(String email, String password) throws IOException {

        String path = "out/EmployeesPassword.txt";
        File passwords = new File(path);
        BufferedWriter out;

        if(passwords.exists()){
            FileWriter fstream = new FileWriter(path, true); //true tells to append data.
            out = new BufferedWriter(fstream);
            out.write("\nE-mail:" + email + "\nPassword:" + password);
            out.close();
        }else{

            FileWriter fileWriter = new FileWriter(path);
            fileWriter.write("SnsUsers Passwords:\n\nE-mail:" + email + "\nPassword:" + password);
            fileWriter.close();

        }

    }

}
